---
title: "Untitled"
author: "Andrew Maloney"
date: "5/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Loading Packages
#Will most likely add more
library(dplyr)
library(bulletxtrctr)
library(x3ptools)
library(randomForest)
library(ggplot2)
library(readr)
library(furrr)
library(stringr)
library(dichromat)
library(future)
library(gridExtra)
library(tidyr)

options(future.globals.maxSize = 4*1024*1024*1024)

data_dir <- "/media/Raven/REU_Refit"
```

```{r}
# Reading in Hamby_173
df <- tibble(path = list.files(path = file.path(data_dir, "Hamby_173"), 
                               pattern = ".x3p", recursive = T, 
                               full.names = T)) %>% 
  mutate(Barrel = str_extract(path, "(Unknown|Barrel)\\d{0,2}") %>% 
           str_remove("Barrel"), 
         Bullet = str_extract(path, "Bullet[12A-Z]") %>% 
           str_remove("Bullet"),
         Land = str_extract(path, "land\\d{1}") %>% 
           str_remove("land")) %>% 
  mutate(Set = "Hamby173") %>%
  mutate(x3p = future_map(path, read_x3p)) %>%
  # Adjust orientation
# I rewrote this so it's a bit clearer. The ~ notation in purrr is pretty concise - no need to define new functions inline.
  mutate(x3p = future_map(x3p, ~x3p_m_to_mum(.) %>% y_flip_x3p()))

# Reading in Hamby_252
df2 <- tibble(path = list.files(path = file.path(data_dir, "Hamby_252"), 
                                pattern = ".x3p", recursive = T, 
                                full.names = T)) %>% 
  mutate(Barrel = str_extract(path, "(Unknown|Barrel)\\d{0,2}") %>% 
           str_remove("Barrel"), 
         Bullet = str_extract(path, "Bullet[12A-Z]") %>% 
           str_remove("Bullet"), 
         Land = str_extract(path, "Bullet [12A-Z]-[123456]") %>% 
           str_remove("Bullet [12A-Z]-")) %>% 
  mutate(Set = "Hamby252") %>%
  mutate(x3p = future_map(path,read_x3p))  %>%
  # Adjust orientation
  mutate(x3p = future_map(x3p, ~x3p_m_to_mum(.) %>% rotate_x3p(angle = -90) %>% y_flip_x3p()))

# One big data set - easier to debug the code if you do everything in one big go.
hamby <- bind_rows(df, df2)
rm(df, df2)
```

```{r}
plan(multicore) # use all the cores at once

hamby <- hamby %>%
  mutate(
    CrossSection = future_map_dbl(x3p, x3p_crosscut_optimize, minccf = 0.9, span = 0.3, percent_missing = 25)
  )
head(select(hamby, -path, -x3p), 5)
#head(df2, 25)

```

```{r}
#Cross Sections
hamby <- hamby %>% 
  mutate(CrossCut = future_map2(.x = x3p, .y = CrossSection, .f = x3p_crosscut))

crosscuts <- hamby %>% 
  tidyr::unnest(CrossCut)

```

```{r}
#Grooves
hamby <- hamby %>% 
  mutate(Grooves = CrossCut %>% future_map(.f = cc_locate_grooves, method = "rollapply", smoothfactor = 15, return_plot = T)) 

grooves <- hamby %>% tidyr::unnest(Grooves)
head(grooves, 10)
head(select(hamby, -path, -x3p, -CrossCut), 5)

# Need to check the grooves and set manually for now...
```
# When run in interactive mode, a shiny app can be used to set smarter grooves.
```{r get-grooves-interactive, echo = FALSE}
library(shiny)

hamby <- hamby %>%
  mutate(id = paste(Set, Barrel, Bullet, Land, sep = "-"))

saved_grooves_location <- "H173_H252_Grooves_data.rda"
if (file.exists(saved_grooves_location)) {
  hamby$Grooves <- readRDS(saved_grooves_location)
}

if (interactive()) { # only run when you're manually running chunks... don't run when the whole document is compiled.
  shinyApp(
    ui = fluidPage(
      selectInput("k", "Investigate kth plot:",
                  selected = 1,
                  choices = (1:length(hamby$Grooves)) %>% set_names(hamby$id)
      ),
      textOutput("groovelocations"),
      actionButton("confirm", "Confirm"),
      actionButton("save", "Save"),
      plotOutput("groovePlot", click = "plot_click"),
      verbatimTextOutput("info")
    ),
    
    server = function(input, output, session) {
      output$groovePlot <- renderPlot({
        k <- as.numeric(input$k)
        p <- hamby$Grooves[[k]]$plot
        
        p
      })
      output$groovelocations <- renderText({
        paste(
          "Left Groove: ", hamby$Grooves[[as.numeric(input$k)]]$groove[1],
          " Right Groove: ", hamby$Grooves[[as.numeric(input$k)]]$groove[2]
        )
      })
      observeEvent(input$confirm, {
        cat(paste(hamby$id[as.numeric(input$k)], "\n"))
        updateSelectInput(session, "k", "Investigate kth plot:",
                          selected = as.numeric(input$k) + 1,
                          choices = (1:length(hamby$Grooves)) %>% set_names(hamby$id)
        )
      })
      observeEvent(input$save, {
        saveRDS(hamby$Grooves, file = saved_grooves_location)
        message("groove data saved\n")
      })
      
      observeEvent(input$plot_click, {
        k <- as.numeric(input$k)
        xloc <- input$plot_click$x
        
        gr <- hamby$Grooves[[k]]$groove
        if (abs(gr[1] - xloc) < abs(gr[2] - xloc)) {
          hamby$Grooves[[k]]$groove[1] <<- xloc
        } else {
          hamby$Grooves[[k]]$groove[2] <<- xloc
        }
        output$groovePlot <- renderPlot({
          k <- as.numeric(input$k)
          p <- hamby$Grooves[[k]]$plot +
            geom_vline(xintercept = hamby$Grooves[[k]]$groove[1], colour = "green") +
            geom_vline(xintercept = hamby$Grooves[[k]]$groove[2], colour = "green")
          
          p
        })
      })
      output$info <- renderText({
        paste0("x=", input$plot_click$x, "\ny=", input$plot_click$y)
      })
    },
    options = list(height = 500)
  )
  saveRDS(hamby$Grooves, file = saved_grooves_location)
} else {
  if (!file.exists(saved_grooves_location)) {
    message("run script in interactive mode to fix grooves")
  } else {
    hamby$Grooves <- readRDS(saved_grooves_location)
  }
}

```

```{r}
#Signatures
hamby <- hamby %>% mutate(Signatures = future_map2(.x = CrossCut, .y = Grooves, .f = cc_get_signature, span = 0.75, span2 = .03)) #Obtaining Signatures Hamby_173

Signatures <- hamby %>% select(id, Set, Barrel, Bullet, Land, Signatures) %>% tidyr::unnest()
head(Signatures, 5)
#head(Grooves_252, 1000)

qplot(data = filter(Signatures, id %in% unique(id)[1:6]), x = x, y = sig, geom = "line", color = id) # Plot a few to see what they look like
Signatures %>%
  filter(Barrel != "Unknown") %>% 
ggplot(data = ., aes(x = x, y = sig, color = Land)) + 
  geom_line() + 
  facet_grid(Set + paste("Bullet", Bullet) ~ sprintf("Barrel %02s", Barrel)) # put the barrels in the right order
# Looking for major issues - grooves not set correctly (large deviations at beginning or end of a line)
```

```{r}

comparisons <- crossing(Bullet1 = hamby$id, Bullet2 = hamby$id) %>%
  left_join(nest(hamby, -id) %>% set_names(c("Bullet1")))
dfx <- df %>% mutate(Bullet_Land = paste(Barrel, Bullet, Land, sep = "-")) %>% nest(-Bullet_Land) 

df2x<- df2 %>% mutate(Bullet_Land = paste(Barrel, Bullet, Land, sep = "-")) %>% nest(-Bullet_Land)

Comparison_173 <- dfx %>%
  crossing(Land1 = unique(.$Bullet_Land)) %>% 
      left_join(set_names(dfx, c("Land1", "data2"))) %>% rename(Land2 = Bullet_Land) %>% mutate(Land1 = factor(Land1), Land2 = factor(Land2))

Comparison_252 <- df2x %>% 
  crossing(Land1 = unique(.$Bullet_Land)) %>% 
    left_join(set_names(df2x, c("Land1", "data2"))) %>% rename(Land2 = Bullet_Land) %>% mutate(Land1 = factor(Land1), Land2 = factor(Land2))

dfx <- dfx %>% tidyr::unnest()
df2x <- df2x %>% tidyr::unnest()


head(Comparison_173)
Comparison_173 <- Comparison_173 %>% select(Land1, Land2)
Comparison_252 <- Comparison_252 %>% select(Land1, Land2)
```

```{r}
Compare_173x <- Comparison_173 %>% mutate(Aligned = future_map2(.x = Land1, .y = Land2, .f = function(xx, yy) {
    Land1 <- dfx$Signatures[dfx$Bullet_Land == xx][[1]]
    Land2 <- dfx$Signatures[dfx$Bullet_Land == yy][[1]]
    Land1$Bullet <- "First-Land"
    Land2$Bullet <- "Second-Land"
    
    sig_align(Land1$sig, Land2$sig)
  })
)


Compare_252x <- Comparison_252 %>% mutate(Aligned = future_map2(.x = Land1, .y = Land2, .f = function(xx, yy) {
    Land1 <- df2x$Signatures[df2x$Bullet_Land == xx][[1]]
    Land2 <- df2x$Signatures[df2x$Bullet_Land == yy][[1]]
    Land1$Bullet <- "First-Land"
    Land2$Bullet <- "Second-Land"
    
    sig_align(Land1$sig, Land2$sig)
  })
)


head(Compare_252x, 10)

```


```{r}
Compare_173x <- Compare_173x %>% mutate(ccf0 = Aligned %>% future_map_dbl(.f = function(x) extract_feature_ccf(x$lands)))
Compare_173x <- Compare_173x %>% mutate(lag0 = Aligned %>% future_map_dbl(.f = function(x) extract_feature_lag(x$lands)))
Compare_173x <- Compare_173x %>% mutate(D0 = Aligned %>% future_map_dbl(.f = function(x) extract_feature_D(x$lands)))
Compare_173x <- Compare_173x %>% mutate(length0 = Aligned %>% future_map_dbl(.f = function(x) extract_feature_length(x$lands)))
Compare_173x <- Compare_173x %>% mutate(overlap0 = Aligned %>% future_map_dbl(.f = function(x) extract_feature_overlap(x$lands)))

Compare_173x <- Compare_173x %>% mutate(striae = Aligned %>% future_map(.f = sig_cms_max, span = 35))

Compare_173x <- Compare_173x %>% mutate(cms_per_m = future_map2(striae, Aligned, .f = function(x, y){
  extract_feature_cms_per_mm(x$lines, y$lands, resolution = 1.5625)
}), matches0 = striae %>% map_dbl(.f = function(x){
  bulletxtrctr:::extract_helper_feature_n_striae(x$lines, type = "peak", match = TRUE)
}), mismatches0 = striae %>% map_dbl(.f = function(x){
  bulletxtrctr:::extract_helper_feature_n_striae(x$lines, type = "peak", match = FALSE)
}))




Compare_252x <- Compare_252x %>% mutate(ccf0 = Aligned %>% future_map_dbl(.f = function(x) extract_feature_ccf(x$lands)))
Compare_252x <- Compare_252x %>% mutate(lag0 = Aligned %>% future_map_dbl(.f = function(x) extract_feature_lag(x$lands)))
Compare_252x <- Compare_252x %>% mutate(D0 = Aligned %>% future_map_dbl(.f = function(x) extract_feature_D(x$lands)))
Compare_252x <- Compare_252x %>% mutate(length0 = Aligned %>% future_map_dbl(.f = function(x) extract_feature_length(x$lands)))
Compare_252x <- Compare_252x %>% mutate(overlap0 = Aligned %>% future_map_dbl(.f = function(x) extract_feature_overlap(x$lands))) 

Compare_252x <- Compare_252x %>% mutate(striae = Aligned %>% future_map(.f = sig_cms_max, span = 35))

Compare_252x <- Compare_252x %>% mutate(cms_per_m = future_map2(striae, Aligned, .f = function(x, y){
  extract_feature_cms_per_mm(x$lines, y$lands, resolution = 1.5625)
}), matches0 = striae %>% future_map_dbl(.f = function(x){
  bulletxtrctr:::extract_helper_feature_n_striae(x$lines, type = "peak", match = TRUE)
}), mismatches0 = striae %>% future_map_dbl(.f = function(x){
  bulletxtrctr:::extract_helper_feature_n_striae(x$lines, type = "peak", match = FALSE)
}))
```

```{r}
# Splitting "String" into seperate Columns for Hamby_173
Compare_173x <- Compare_173x %>% mutate(BarrelA = gsub("([0-9]{1,2}|Unknown)-([1-2A-Z])-([1-6])", "\\1", Land1))
Compare_173x <- Compare_173x %>% mutate(BarrelB = gsub("([0-9]{0,2}|Unknown)-([1-2A-Z])-([1-6])", "\\1", Land2))
Compare_173x <- Compare_173x %>% mutate(BulletA = gsub("([0-9]{1,2}|Unknown)-([1-2A-Z])-([1-6])", "\\2", Land1))
Compare_173x <- Compare_173x %>% mutate(BulletB = gsub("([0-9]{1,2}|Unknown)-([1-2A-Z])-([1-6])", "\\2", Land2))
Compare_173x <- Compare_173x %>% mutate(LandA = gsub("([0-9]{1,2}|Unknown)-([1-2A-Z])-([1-6])", "\\3", Land1))
Compare_173x <- Compare_173x %>% mutate(LandB = gsub("([0-9]{1,2}|Unknown)-([1-2A-Z])-([1-6])", "\\3", Land2))


 
Compare_252x <- Compare_252x %>% mutate(BarrelA = gsub("([0-9]{1,2}|Unknown)-([1-2A-Z])-([1-6])", "\\1", Land1))
Compare_252x <- Compare_252x %>% mutate(BarrelB = gsub("([0-9]{0,2}|Unknown)-([1-2A-Z])-([1-6])", "\\1", Land2))
Compare_252x <- Compare_252x %>% mutate(BulletA = gsub("([0-9]{1,2}|Unknown)-([1-2A-Z])-([1-6])", "\\2", Land1))
Compare_252x <- Compare_252x %>% mutate(BulletB = gsub("([0-9]{1,2}|Unknown)-([1-2A-Z])-([1-6])", "\\2", Land2))
Compare_252x <- Compare_252x %>% mutate(LandA = gsub("([0-9]{1,2}|Unknown)-([1-2A-Z])-([1-6])", "\\3", Land1))
Compare_252x <- Compare_252x %>% mutate(LandB = gsub("([0-9]{1,2}|Unknown)-([1-2A-Z])-([1-6])", "\\3", Land2))


head(Compare_252x, 40)


```


```{r}
Compare_173x <- Compare_173x %>% mutate(Features = future_map2(.x = Aligned, .y = striae, .f = extract_features_all, resolution = 1.5625))
Compare_173x <- Compare_173x %>% mutate(Legacy_Features = future_map(striae, extract_features_all_legacy, resolution = 1.5625))
Compare_173x <- Compare_173x %>% tidyr::unnest(Legacy_Features)

Compare_252x <- Compare_252x %>% mutate(Features = future_map2(.x = Aligned, .y = striae, .f = extract_features_all, resolution = 1.5625))
Compare_252x <- Compare_252x %>% mutate(Legacy_Features = future_map(striae, extract_features_all_legacy, resolution = 1.5625))
Compare_252x <- Compare_252x %>% tidyr::unnest(Legacy_Features)

```

```{r}
Compare_173x$rfscore <- predict(rtrees, newdata = Compare_173x, type = "prob")[,2]
Compare_252x$rfscore <- predict(rtrees, newdata = Compare_252x, type = "prob")[,2]


```

```{r}
Bullet_Scores_173x <- Compare_173x %>% group_by(BulletA, BulletB) %>% tidyr::nest()
Bullet_Scores_173x <- Bullet_Scores_173x %>% mutate(Bullet_Score = data %>% future_map_dbl(.f = function(d) max(compute_average_scores(land1 = d$LandA, land2 = d$LandB, d$rfscore))))
Bullet_Scores_173x %>% select(-data)

Bullet_Scores_252x <- Compare_252x %>% group_by(BulletA, BulletB) %>% tidyr::nest()
Bullet_Scores_252x <- Bullet_Scores_252x %>% mutate(Bullet_Score = data %>% future_map_dbl(.f = function(d) max(compute_average_scores(land1 = d$LandA, land2 = d$LandB, d$rfscore))))
Bullet_Scores_252x %>% select(-data)

```

```{r}
Bullet_Scores_173x <- Bullet_Scores_173x %>% mutate(data = data %>% future_map(.f = function(d){
  d$samepath = bullet_to_land_predict(land1 = d$LandA, land2 = d$LandB, d$rfscore, difference = 0.1)
  d
}))

Bullet_Scores_173x %>% tidyr::unnest(data)
head(Bullet_Scores_173x, 100)


Bullet_Scores_252x <- Bullet_Scores_252x %>% mutate(data = data %>% future_map(.f = function(d){
  d$samepath = bullet_to_land_predict(land1 = d$LandA, land2 = d$LandB, d$rfscore, difference = 0.1)
  d
}))

Bullet_Scores_252x

```

```{r}
#Feature Density Plots for Hamby_173


Compare_173x <- Compare_173x %>% 
  mutate(KM_KNM = if_else(ccf >= 0.50, "Known_Match", "Known_Non_Match")) %>%
      mutate(KM_KNM = factor(KM_KNM)) 

Compare_173x %>% ggplot(aes(cms, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") + scale_x_continuous(limits = c(0, 3.5)) +
      ggtitle("Cms Density Plot")

Compare_173x %>% ggplot(aes(non_cms, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") +
      ggtitle("Non_cms Density Plot")

Compare_173x %>% ggplot(aes(matches, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") +
      ggtitle("#Matches Density Plot")

Compare_173x %>% ggplot(aes(mismatches, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") +
      ggtitle("#MisMatches Density Plot")

Compare_173x %>% ggplot(aes(D, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") + 
      ggtitle("Average Distance Density Plot")

Compare_173x %>% ggplot(aes(sum_peaks, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") + scale_x_continuous(limits = c(0, 20)) +
      ggtitle("Sum of Peaks Density Plot")

Compare_173x %>% ggplot(aes(ccf, fill = KM_KNM)) + 
  geom_density(position = "identity", alpha = 0.50) + 
    scale_fill_brewer(palette = "Paired") +
      ggtitle("Ccf Density Plot")

head(Compare_173x, 25)


```

```{r}
#Feature Density Plots for Hamby_252

Compare_252x <- Compare_252x %>% mutate(KM_KNM = if_else(ccf >= 0.50, "Known_Match", "Known_non_Match")) %>% 
  mutate(KM_KNM = factor(KM_KNM))

Compare_252x %>% ggplot(aes(cms, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") + scale_x_continuous(limits = c(0, 3.5)) +
      ggtitle("Cms Density Plot")

Compare_252x %>% ggplot(aes(non_cms, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") +
      ggtitle("Non_cms Density Plot")

Compare_252x %>% ggplot(aes(matches, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") +
      ggtitle("#Matches Density Plot")

Compare_252x %>% ggplot(aes(mismatches, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") +
      ggtitle("#MisMatches Density Plot")

Compare_252x %>% ggplot(aes(D, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") + 
      ggtitle("Average Distance Density Plot")

Compare_252x %>% ggplot(aes(sum_peaks, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.55) + 
    scale_fill_brewer(palette = "Paired") + scale_x_continuous(limits = c(0, 20)) +
      ggtitle("Sum of Peaks Density Plot")

Compare_252x %>% ggplot(aes(ccf, fill = KM_KNM)) + 
  geom_density(position = "identity", alpha = 0.50) + 
    scale_fill_brewer(palette = "Paired") +
      ggtitle("Ccf Density Plot")


```

```{r}
#Combined plots using facet_wrap for hamby_173
HambyDataLong <- gather(Compare_173x, key="measure", value="value", c("ccf", "cms", "non_cms", "matches", "mismatches", "D", "sum_peaks"))

HambyDataLong %>% ggplot(aes(value, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.50)+
    facet_wrap(~measure, ncol = 4, scales = "free")+
      scale_fill_brewer(palette = "Paired") + theme_bw()+
        ggtitle("Marginal Density for Features")
    
```

```{r}
#Combined plots using facet_wrap for hamby_252
HambyDataLong_2 <- gather(Compare_252x, key="measure", value="value", c("ccf", "cms", "non_cms", "matches", "mismatches", "D", "sum_peaks"))

HambyDataLong_2 %>% ggplot(aes(value, fill = KM_KNM))+
  geom_density(position = "identity", alpha = 0.50)+
    facet_wrap(~measure, ncol = 4, scales = "free")+
      scale_fill_brewer(palette = "Paired") + theme_bw()+
        ggtitle("Marginal Density for Features")

```





